services:
  pc_simulation:
    build: .
    container_name: ros2_jazzy_pc
    network_mode: host
    # privileged: true จำเป็นสำหรับ GPU (Gazebo) และ X11 display ฝั่ง PC
    # ถ้าไม่ใช้ Gazebo หรือ GPU สามารถเปลี่ยนเป็น cap_add ได้เช่นเดียวกับฝั่ง rpi5
    privileged: true
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-30}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/ros2_ws/src:rw
    restart: unless-stopped
    stdin_open: true
    tty: true
